//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Possessions
    {
        public Possessions()
        {
            this.PossessionsImages = new HashSet<PossessionsImages>();
            this.PossessionsIssues = new HashSet<PossessionsIssues>();
        }
    
        public int PossessionID { get; set; }
        public int DriverID { get; set; }
        public int VehicleID { get; set; }
        public string RegistrationNo { get; set; }
        public System.DateTime PossessionDateTime { get; set; }
        public float ODOMeterPossissionTime { get; set; }
        public Nullable<bool> ETagHolderPossissionTime { get; set; }
        public Nullable<bool> FootMattsPossissionTime { get; set; }
        public Nullable<bool> CleanlinessPossissionTime { get; set; }
        public Nullable<float> EngineServiceDuePossissionTime { get; set; }
        public Nullable<float> TransmissionServiceDuePossissionTime { get; set; }
        public Nullable<System.DateTime> NoticeDateReturn { get; set; }
        public string NoticeRemarks { get; set; }
        public Nullable<System.DateTime> ReturnDateTime { get; set; }
        public Nullable<float> ODOMeterReturn { get; set; }
        public Nullable<bool> ETagHolderReturn { get; set; }
        public Nullable<bool> FootMattsReturn { get; set; }
        public Nullable<bool> CleanlinessReturn { get; set; }
        public Nullable<bool> EngineServiceDueReturn { get; set; }
        public Nullable<bool> TransmissionServiceDueReturn { get; set; }
        public string Feedback { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public Nullable<int> PossessionByUserID { get; set; }
        public Nullable<int> ReturnByUserID { get; set; }
        public string PossessionTimeDriverSignature { get; set; }
        public string PossessionTimeContractorSignature { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual Vehicles Vehicles { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<PossessionsImages> PossessionsImages { get; set; }
        public virtual ICollection<PossessionsIssues> PossessionsIssues { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
