//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PossessionsImages
    {
        public int PossessionImageID { get; set; }
        public int PossessionID { get; set; }
        public string PossessionTimeImagePath { get; set; }
        public string PossessionTimeImagePathThumbnail { get; set; }
        public string ReturnTimeImagePath { get; set; }
        public string ReturnTimeImagePathThumbnail { get; set; }
    
        public virtual Possessions Possessions { get; set; }
    }
}
