//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Possessions = new HashSet<Possessions>();
            this.Possessions1 = new HashSet<Possessions>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public byte[] Password { get; set; }
        public int UserTypeID { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Possessions> Possessions { get; set; }
        public virtual ICollection<Possessions> Possessions1 { get; set; }
    }
}
