//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CurrentPossessions
    {
        public int PossessionID { get; set; }
        public System.DateTime PossessionDateTime { get; set; }
        public string Rego { get; set; }
        public string DriverName { get; set; }
        public System.DateTime DriverDateOfBirth { get; set; }
        public string VehicleDetails { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    }
}
