//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NoticedVehicles
    {
        public int PossessionID { get; set; }
        public string RegistrationNo { get; set; }
        public string DriverName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public string NoticeRemarks { get; set; }
        public Nullable<System.DateTime> ReturnDateTime { get; set; }
        public Nullable<bool> IsReturn { get; set; }
    }
}
