//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclesIssues
    {
        public int VehicleIssueID { get; set; }
        public int VehicleID { get; set; }
        public string IssueDetails { get; set; }
        public string ImagePath { get; set; }
        public string ImageThumbnailPath { get; set; }
        public Nullable<System.DateTime> IssueReportDate { get; set; }
        public bool IsIssueFixed { get; set; }
        public Nullable<System.DateTime> IssueFixeDate { get; set; }
    
        public virtual Vehicles Vehicles { get; set; }
    }
}
