//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        public Vehicles()
        {
            this.Possessions = new HashSet<Possessions>();
            this.VehiclesImages = new HashSet<VehiclesImages>();
            this.VehiclesIssues = new HashSet<VehiclesIssues>();
        }
    
        public int VehicleID { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<System.DateTime> RegistrationExpiryDate { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public string Color { get; set; }
        public Nullable<float> FirstODOMeterReading { get; set; }
        public Nullable<float> LastODOMeterReading { get; set; }
        public Nullable<float> EngineServiceDueKM { get; set; }
        public Nullable<float> TransmissionServiceDueKM { get; set; }
        public Nullable<bool> ETagHolder { get; set; }
        public Nullable<bool> FootMatts { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Possessions> Possessions { get; set; }
        public virtual ICollection<VehiclesImages> VehiclesImages { get; set; }
        public virtual ICollection<VehiclesIssues> VehiclesIssues { get; set; }
    }
}
