//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VPSEntities : DbContext
    {
        public VPSEntities()
            : base("name=VPSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<Possessions> Possessions { get; set; }
        public virtual DbSet<PossessionsImages> PossessionsImages { get; set; }
        public virtual DbSet<PossessionsIssues> PossessionsIssues { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vehicles> Vehicles { get; set; }
        public virtual DbSet<VehiclesImages> VehiclesImages { get; set; }
        public virtual DbSet<VehiclesIssues> VehiclesIssues { get; set; }
        public virtual DbSet<V_AvailableVehicles> V_AvailableVehicles { get; set; }
        public virtual DbSet<V_CurrentPossessions> V_CurrentPossessions { get; set; }
        public virtual DbSet<V_NoticedVehicles> V_NoticedVehicles { get; set; }
    }
}
